services:
  db:
    image: postgres:18
    container_name: skillbox-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: skillbox_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  app:
    build: .
    container_name: skillbox-java-spring
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/skillbox_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8082:8082"

volumes:
  pgdata: